### PR TITLE
Table of supported transports and data links.

### PR DESCRIPTION
**Pull request by ralph-lange**

### CODE REVIEW

**Comment by ralph-lange** [comment]
@julibert, @FranFin, I created a first draft of a special feature table explaining the supported transports and data link protocols, depending on the RTOS. Could you please set the markers correctly? You may also consider to add markers for work-in-progress. Is the title naming transports and data links correct? Should we name it just data link protocols or just transport protocols for simplicity?

**Comment by pablogs9** [comment]
I like the naming and I would mark the WIP transports because we hope to have some of them soon (e.g UDP on Zephyr). 

On the other hand if we distinguish between UDP/ETH and UDP/80211, what do you think about distinguishing between Serial/UART and Serial/USB? Because on Zephyr we have support for both of them.

If you are ok with this, I can commit on this same branch with our changes.

Thanks!

**Comment by ralph-lange** [comment]
Thank you, @pablogs9, for reviewing the table. Yes, please continue working on this. I like the idea of splitting up the serial column.

**Comment by pablogs9** [comment]
One more thing, what do you think about distinguish between RTOS/Platform instead of only by RTOS? Because for example we support Radio Bluetooth transport on the FreeRTOS+Crazyflie platform but it make less sense on the Olimex+FreeRTOS platform because it has no radio IC by default...

Same happens with Serial USB, we have it on Olimex+Zephyr (out of the box with the RTOS) but not yet on Olimex+FreeRTOS (requires a specific transport over the HAL layer provided by STM32CubeMX that is not ready).

What do you think about this?

**Comment by ralph-lange** [comment]
@pablogs9, I would not distinguish the different hardware platforms on this page but make general statements as far as possible. If somebody wants to bring micro-ROS on a new board, he or she will always have to work on the board support.

In my opinion, the mentioned details on crazyflie etc. should go into the `supported hardware` page. Is this fine for you?

**Comment by pablogs9** [comment]
It's ok for me, I am going to commit some minor changes to the board as we previously talked.

**Comment by ralph-lange** [comment]
Yep, perfect. Looking forward to your contributions, @pablogs9!

**Comment by ralph-lange** [comment]
Looks good. With the mutual reviews, I just merged it.

**Pull request merged**
