### PR TITLE
Feature/advanced tutorials linux

### PR DESCRIPTION
**Pull request by ralph-lange**
Fixes the link issue reported by @christophebedard.

### CODE REVIEW

**Comment by ralph-lange** [comment]
Now, we have quite many menus inside the tutorials section, but we actually decided for the "Advanced tutorials for Linux" menu in the conf call on Wednesday.

**Comment by pablogs9** [comment]
Is this ok for you @christophebedard?

**Comment by pablogs9** [comment]
Is the original post inside Nuttx advanced tutorial removed @ralph-lange ?

**Comment by christophebedard** [comment]
Looks good to me! Thank you @ralph-lange and @pablogs9!

**Comment by ralph-lange** [comment]
> 
> 
> Is the original post inside Nuttx advanced tutorial removed @ralph-lange ?

Now it is removed. Thank you for this hint, @pablogs9

**Pull request merged**
