### PR TITLE
Added status table for bloom releases of ros2/rclc repo

### PR DESCRIPTION
**Pull request by JanStaschulat**

### CODE REVIEW

**Review by norro — APPROVED** [review]
Very nice! I should do this for system modes as well.

**Comment by JanStaschulat** [comment]
Has anyone an idea, how to merge multiple rows for "Architecture" in a markdown table like
```
| Package | Release |      Architecture          |
|         |         | amd64   | arm64  |  armhf  |
```

I tried with 
```
|             |          Grouping           ||
```
https://stackoverflow.com/questions/46621765/can-i-merge-table-rows-in-markdown

and 
```
| Span <td colspan=3>triple  <td colspan=2>double
```
https://stackoverflow.com/questions/23571724/github-markdown-colspan

Both approaches did not work.

**Comment by jamoralp** [comment]
@JanStaschulat , you can try generating the sub-table with markdown, then convert it to html code 
 using [this](https://www.mobilefish.com/services/markdown/markdown.php), for example, finally embed the resulting html into the markdown outer cell. See [this](https://stackoverflow.com/questions/43591906/nested-tables-in-markdown).

**Review by FranFin — APPROVED** [review]

**Comment by JanStaschulat** [comment]
@jamoralp thanks for the trick. I'd rather keep the table in markdown. It is already quite a number of links. If you are fine with the table as is, could you approve and merge the PR?

**Review by ralph-lange — APPROVED** [review]

**Comment by JanStaschulat** [comment]
updated REAMDE in micro-ros/rclc
https://github.com/micro-ROS/rclc/pull/60

**Pull request merged**
