### PR TITLE
Application components can access the RTOS directly

### PR DESCRIPTION
**Pull request by gseqBE**
The image is a bit confusing for new users(I had the question).

Fixed pptx(layout section) by extending  "application component" to the RTOS layer to indicate that the user application has access to the RTOS also. An example would be creating a thread independent of micro-ros.

Please see [this slack history](https://micro-ros.slack.com/archives/CNC141G0N/p1650547982631279) for reference.

### CODE REVIEW

**Comment by pablogs9** [comment]
The image has red underlines

image

**Comment by pablogs9** [comment]
@ralph-lange thoughts about this?

**Review by ralph-lange — COMMENTED** [review]
Thank you for the PR. I appreciate PRs on improving the documentation very much! However, I have to admit that prefer the current drawing – because of simplicity and clarity.

Two thoughts:
1. In such layered architectures, it is not uncommon that higher layers skip one or more lower layers and access even lower layers directly. For example, rcl and rclc make numerous POSIX calls (which is even not depicted in the proposed new drawing). If including these calls in the drawing, it would become very complicated.
2. The new drawing also indicates that there might be non-micro-ROS applications on the MCU, in parallel to micro-ROS. In my opinion, such drawings never make the claim that there are no additional components. For example, if one draws a WiFi network stack on a smartphone OS, this does not indicate that there is no Bluetooth 😊 And, for the micro-ROS architecture, I could think of even more components: The MCU might run multiple OS using a hypervisor. Or, there might be an application component that uses Micro-XRCE-DDS but not rmw and rcl+rclc. Again, if including all these options in the drawing, it would become very complicated.

Please note that the current drawing fits well with commonly used representations of the ROS 2 stack (e.g., https://aws.amazon.com/de/blogs/robotics/ros2-foxy-fitzroy-robot-development/).

**Comment by gseqBE** [comment]
@pablogs9 Redlines fixed.
@ralph-lange Thank you for the feedback! I understand what you are saying.. and that it would make the diagram more busy.
When I first was looking to microros, the diagram threw me off a little as it illustrated that there was no user access to the OS.. for people with embedded backgrounds, that could be the first thing they look for.. hence the suggestion.

Anyway, no harm done, please feel free to deny this PR. Hope to help more on microros(once I get the udp-microros issue on my setup resolved :) )

**Comment by ralph-lange** [comment]
@gseqBE, I'll deny the PR. As already written, I really appreciate PRs to the documentation. Perhaps we should add one or two sentences about the modularity w.r.t. to the layers and the possibility to skip layers when calling functions of lower layers to the _Features and Architecture_ page at https://micro.ros.org/docs/overview/features/.

I assume that with the Humble release, there is a lot to revise. Your support would be of great help!

**Pull request closed without merging**
