### PR TITLE
Udate architecture diagram.

### PR DESCRIPTION
**Pull request by BorjaOuterelo**
Update architecture diagram to follow same theme and use concepts from decision paper.

### CODE REVIEW

**Comment by BorjaOuterelo** [comment]
@ralph-lange thanks for the review. Already addressed your comment on clarity by:

- Changing the 3D effect. It may be more clear now.
- Adding some more colours and a legend trying to clarify package/source code origin.

The C API I have made the box of rcl to reach from one end to the other on the Client library. I want to state also that most of the rcl extensions use that same rcl.

**Comment by ralph-lange** [comment]
Hi @BorjaOuterelo, the diagram looks much better now. The coloring is a very good idea! I propose to place micro-ROS rclc inside the orange C API shape. Otherwise a reader might think that we want to provide three APIs (rcl, rclc, rclcpp).

**Comment by BorjaOuterelo** [comment]
@ralph-lange I added your API susggestion. It seems more clear now. Right?

**Comment by ralph-lange** [comment]
Should/may we already add FreeRTOS in the diagram?

**Comment by BorjaOuterelo** [comment]
I added it. It mess a bit the RTOS part, but it states that we have support for both, NuttX and FreeRTOS.

**Pull request merged**
