### PR TITLE
Added blogpost on esp32 port.

### PR DESCRIPTION
**Pull request by FranFin**

### CODE REVIEW

**Review by jamoralp — APPROVED** [review]

**Comment by pablogs9** [comment]
Should we add the ESP32 to the supported platforms page?

**Comment by FranFin** [comment]
Yes, I'd say so.

**Comment by pablogs9** [comment]
In this PR or in other?

**Comment by FranFin** [comment]
In the same. I'll take care of it.

**Review by pablogs9 — APPROVED** [review]

**Pull request merged**
