### PR TITLE
Move programming with rcl and rclc before advanced tutorials.

### PR DESCRIPTION
**Pull request by ralph-lange**
@pablogs9, @JanStaschulat: I've also added distro status badges to the individual programming with rcl and rclc tutorials. Please check whether they are correct!

### CODE REVIEW

**Review by pablogs9 — APPROVED** [review]
LGTM, check CI

**Comment by ralph-lange** [comment]
Hi @pablogs9, I've fixed all links from the previous PR. Any idea for the reason of the last remaining build error?

**Comment by pablogs9** [comment]
Lets see if is related to this PR or is an error in master: https://github.com/micro-ROS/micro-ROS.github.io/pull/340

**Comment by pablogs9** [comment]
Not related to this PR. @Acuadros95 can you take a look on this error?

**Comment by Acuadros95** [comment]
The `Cleaning up` section of the parameters tutorial was inside a misformatted code block, caused by missing indentation in the previous section.

My last commit should fix it.

**Comment by pablogs9** [comment]
Thanks a lot!

**Review by pablogs9 — APPROVED** [review]

**Comment by ralph-lange** [comment]
Thank you very much, @Acuadros95

**Pull request merged**
